STATE_INITIALIZED = 'INITIALIZED'
STATE_SUCCESS = 'SUCCESS'
STATE_FAILED = 'FAILED'

STATES = [
    (STATE_INITIALIZED, 'Initialized'),
    (STATE_SUCCESS, 'Success'),
    (STATE_FAILED, 'Failed'),
]

HTTP_OK = 200
